### ISSUE TITLE
Post List에서 댓글 수가 안맞는 문제

### ISSUE THREAD

**Issue by realstone** [LaunchArea/fitter#19]
댓글 수가 실제 댓글보다 많게 표시됨

**Comment by JackYoon** [comment]
Come from https://github.com/LaunchArea/fitter/blob/master/parse/cloud/main.js#L121
Saving of comment always increase `Post.commentCount`.

**Comment by realstone** [comment]
새로운 Comment 입력시에만 (수정할때 제외) increment 되도록 수정 완료
